a=input('Enter a value for a:')
b=input('Enter a value for b:')
a=int(a)
b=int(b)
c=(a + b)
d=(a - b)
e=(a * b)
f=(a / b)
print('Addition:', c)
print('Diffrence:', d)
print('Product:', e)
print('Division:', f)
